name: Build and Run Docker Image

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t moveho/ci .

      - name: Run Docker Container
        run: docker run -p 4000:4000 moveho/ci
