name: Build and Run Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-docker-image .

      - name: Run Docker Container
        run: docker run -p 4000:4000 my-docker-image
